config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :posts, only: [:index, :show] do
    resources :comments, :only => [:create]
  end

  namespace :admin do
    root 'welcome#index'
    resources :posts
  end

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/admin/welcome_controller.rb
class Admin::WelcomeController < ApplicationController

  before_action :authenticate_user!

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
	  @post = Post.find(params[:post_id])
	  if user_signed_in?
		@comment = @post.comments.create!(params.require(:comment).permit!)
		redirect_to @post, notice: 'Comment saved'
	  else
	    redirect_to @post, notice: 'You need to be logged in to comment on posts'
	  end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.haml
= form_for([:admin, @post]) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :body
    %br/
    = f.text_area :body
  .actions
    = f.submit

app/views/admin/posts/edit.html.haml
%h1 Editing post
= render 'form'
= link_to 'Show', @post
|
\#{link_to 'Back', posts_path}

app/views/admin/posts/index.html.haml
%h1 Listing posts
%table
  %thead
    %tr
      %th Title
      %th Body
      %th{:colspan => "3"}
  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.body
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_admin_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Post', new_admin_post_path

app/views/admin/posts/new.html.haml
%h1 New post
= render 'form'
= link_to 'Back', posts_path

app/views/admin/welcome/index.html.haml
%h2
  = "Welcome #{current_user.first_name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/posts/index.html.haml
%h1 Listing posts
%table
  %thead
    %tr
      %th Title
      %th Body
      %th{:colspan => "3"}
  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.body
        %td= link_to 'Show', post
= link_to "Back", :root

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
    <strong>Title:</strong>
    <%= @post.title %>
</p>
<p>
    <strong>Body:</strong>
    <%= @post.body %>
</p>
<%= form_for [@post, Comment.new] do |f| %>
    <p>
        <%= f.label :body, "Enter comment" %><br/>
        <%= f.text_area :body %>
    </p>
	<p><%= f.submit "Submit" %></p>	
	<% @post.comments.each do |comment|%>
	    <p>
	        <%= time_ago_in_words(comment.created_at) %> ago<br/>
	        <%= comment.body %>
		</p>
	<% end %>
<% end %>
<%= link_to 'Back', posts_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.haml
-if user_signed_in?
  Signed in
-else
  Signed out
%h2
  Welcome to our little blog test app
-if !user_signed_in?
  %p
    = link_to "Login", new_user_session_path
    = link_to "Sign up", new_user_registration_path
= image_tag "https://placekitten.com/500/280"
%p
  Here is a picture of some cats to make you smile before you get started.
%p
  Wanna see some blog posts? Click
  = link_to "here", posts_path
-if user_signed_in?
  = link_to "Log out", destroy_user_session_path, :method => :delete